### ISSUE TITLE
duplicate paragraph in "Security Considerations"

### ISSUE THREAD

**Issue by ericlagergren** [emanjon/draft-mattsson-cfrg-aes-gcm-sst#8]
The paragraph that starts with "The GCM-SST tag_length SHOULD NOT be smaller than 4 bytes and cannot be larger than 16 bytes." exists twice, but with slightly different wording.

**Comment by emanjon** [comment]
Thanks, that should obviously be fixed. 

I will merge the two paragraphs in -02

**Comment by emanjon** [comment]
Fixed in main
